name: CustomerService CI / CD

on:
  push:
    branches:
      - master
    paths:
      - "CustomerService/**"
      - ".github/workflows/customer-service.yaml"
  workflow_dispatch:

jobs:
  build:
    name: 1. Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore ./CustomerService/CustomerService.sln

      - name: Create .pem files from secrets
        run: |
          echo "${{ secrets.PRIVATE_KEY_PEM }}" > ./CustomerService/CustomerService.Api/private_key.pem
          echo "${{ secrets.PUBLIC_KEY_PEM }}" > ./CustomerService/CustomerService.Api/public_key.pem
        shell: bash

      - name: Build Project
        run: dotnet build ./CustomerService/CustomerService.sln -c Release --no-restore

      - name: Run Unit Tests
        run: dotnet test ./CustomerService/CustomerService.sln -c Release --no-build --verbosity normal

  deploy:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create .pem files from secrets
        run: |
          echo "${{ secrets.PRIVATE_KEY_PEM }}" > ./CustomerService/CustomerService.Api/private_key.pem
          echo "${{ secrets.PUBLIC_KEY_PEM }}" > ./CustomerService/CustomerService.Api/public_key.pem
        shell: bash

      - name: Set up Docker Tag
        id: repo_owner
        run: echo "tag=ghcr.io/$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')/CustomerService:latest" >> $GITHUB_OUTPUT

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./CustomerService
          file: ./CustomerService/CustomerService.Api/Dockerfile
          push: true
          tags: ${{ steps.repo_owner.outputs.tag }}
